version: '3.4'

networks:
  robot:

services:
  django:
    image: python:2.7
    networks: [robot]
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    volumes:
      - ./django/grim:/src
    working_dir: /src
    ports:
      - 8000:8000
    command:
      - bash
      - -c
      - "pip install django; pip install django-cors-headers; python manage.py runserver 0.0.0.0:8000;"
  angular:
    image: node:16
    networks: [robot]
    volumes:
      - ./:/src
    working_dir: /src
    command: npm start
    ports:
      - 4200:4200
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks: [robot]
    depends_on:
      - angular
      - django
